CREATE TABLE USUARIO (
    ID              NUMBER(12) NOT NULL,
    Email           VARCHAR2(50) NOT NULL,
    Senha           VARCHAR2(50) NOT NULL UNIQUE,
    Nome            VARCHAR2(50) NOT NULL,
    DataNascimento  DATE NOT NULL,
    Sexo            CHAR(1) NOT NULL,
        CONSTRAINT PK_USUARIO PRIMARY KEY (ID)
);

CREATE TABLE AMIGOS (
    ID              NUMBER(12) NOT NULL,
    ID_USUARIO      NUMBER(12) NOT NULL,
    ID_AMIGO        NUMBER(12) NOT NULL,
        CONSTRAINT PK_AMIGOS PRIMARY KEY (ID),
        CONSTRAINT FK_AMIGOS_ID_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID),
        CONSTRAINT FK_AMIGOS_ID_AMIGO FOREIGN KEY (ID_AMIGO) REFERENCES USUARIO (ID)
);

CREATE TABLE SOLICITACAO (
    ID              NUMBER(12) NOT NULL,
    ID_USUARIO      NUMBER(12) NOT NULL,
    ID_AMIGO        NUMBER(12) NOT NULL,
        CONSTRAINT PK_SOLICITACAO PRIMARY KEY (ID),
        CONSTRAINT FK_SOLICITACAO_ID_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID),
        CONSTRAINT FK_SOLICITACAO_ID_AMIGO FOREIGN KEY (ID_AMIGO) REFERENCES USUARIO (ID)
);

CREATE TABLE PUBLICACAO (
    ID              NUMBER(12) NOT NULL,
    Texto           VARCHAR2(255) NOT NULL,
    Data            DATE NOT NULL,
        CONSTRAINT PK_PUBLICACAO PRIMARY KEY (ID)
);

CREATE TABLE CURTIDAS (
    ID              NUMBER(12) NOT NULL,
    ID_PUBLICACAO   NUMBER(12) NOT NULL,
    ID_USUARIO      NUMBER(12) NOT NULL,
        CONSTRAINT PK_CURTIDAS PRIMARY KEY (ID),
        CONSTRAINT FK_CURTIDAS_ID_PUBLICACAO FOREIGN KEY (ID_PUBLICACAO) REFERENCES PUBLICACAO(ID),
        CONSTRAINT FK_CURTIDAS_ID_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID)
);

CREATE TABLE COMENTARIOS (
    ID              NUMBER(12) NOT NULL,
    ID_PUBLICACAO   NUMBER(12) NOT NULL,
    ID_USUARIO      NUMBER(12) NOT NULL,
    Texto           VARCHAR2(255) NOT NULL,
    Data            DATE NOT NULL,
        CONSTRAINT PK_COMENTARIOS PRIMARY KEY (ID),
        CONSTRAINT FK_COMENTARIOS_ID_PUBLICACAO FOREIGN KEY (ID_PUBLICACAO) REFERENCES PUBLICACAO(ID),
        CONSTRAINT FK_COMENTARIOS_ID_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID)   
);

CREATE SEQUENCE SEQ_USUARIO
    MINVALUE        1
    MAXVALUE        999999999999
    START WITH      1
    INCREMENT BY    1
    CACHE           50
    NOCYCLE;
    
CREATE SEQUENCE SEQ_AMIGO
    MINVALUE        1
    MAXVALUE        999999999999
    START WITH      1
    INCREMENT BY    1
    CACHE           50
    NOCYCLE;
    
CREATE SEQUENCE SEQ_SOLICITACAO
    MINVALUE        1
    MAXVALUE        999999999999
    START WITH      1
    INCREMENT BY    1
    CACHE           50
    NOCYCLE;
    
CREATE SEQUENCE SEQ_CURTIDAS
    MINVALUE        1
    MAXVALUE        999999999999
    START WITH      1
    INCREMENT BY    1
    CACHE           50
    NOCYCLE;
    
CREATE SEQUENCE SEQ_COMENTARIOS
    MINVALUE        1
    MAXVALUE        999999999999
    START WITH      1
    INCREMENT BY    1
    CACHE           50
    NOCYCLE;

--DROP TABLE USUARIO;
--DROP TABLE AMIGOS;
--DROP TABLE SOLICITACAO;
--DROP TABLE PUBLICACAO;
--DROP TABLE CURTIDAS;
--DROP TABLE COMENTARIOS;
--
--DROP SEQUENCE SEQ_USUARIO;
--DROP SEQUENCE SEQ_AMIGO;
--DROP SEQUENCE SEQ_SOLICITACAO;
--DROP SEQUENCE SEQ_CURTIDAS;
--DROP SEQUENCE SEQ_COMENTARIOS;
                   