CREATE TABLESPACE REDESOCIALDAT
	DATAFILE 'C:\oraclexe\app\oracle\oradata\XE\redesocialdat01.dbf'
	SIZE 100m
	AUTOEXTEND ON NEXT 100m MAXSIZE 2048m;

CREATE USER ADMIN IDENTIFIED BY ADMIN
DEFAULT TABLESPACE REDESOCIALDAT;

GRANT CONNECT, RESOURCE, CREATE VIEW TO ADMIN;

CREATE TABLE USUARIO (
	ID              NUMBER(12) NOT NULL,
	Email           VARCHAR2(50) NOT NULL,
	Senha           VARCHAR2(50) NOT NULL UNIQUE,
	Nome            VARCHAR2(50) NOT NULL,
	DataNascimento  DATE NOT NULL,
	SEXO 	          CHAR(1) NOT NULL,
		CONSTRAINT PK_USUARIO PRIMARY KEY (ID)
);

CREATE TABLE AMIZADE (
	ID				NUMBER(12) NOT NULL,
	ID_USUARIO_1    NUMBER(12) NOT NULL,
	ID_USUARIO_2    NUMBER(12) NOT NULL,
		CONSTRAINT PK_AMIZADE PRIMARY KEY (ID),
		CONSTRAINT FK_AMIZADE_ID_USUARIO_1 FOREIGN KEY (ID_USUARIO_1) REFERENCES USUARIO (ID),
		CONSTRAINT FK_AMIZADE_ID_USUARIO_2 FOREIGN KEY (ID_USUARIO_2) REFERENCES USUARIO (ID)
);

CREATE TABLE SOLICITACAO_AMIZADE (
	ID				NUMBER(12) NOT NULL,
	ID_SOLICITANTE	NUMBER(12) NOT NULL,
	ID_SOLICITADO   NUMBER(12) NOT NULL,
		CONSTRAINT PK_SOLICITACAO_AMIZADE PRIMARY KEY (ID),
		CONSTRAINT FK_SOLICITACAO_ID_SOLICITANTE FOREIGN KEY (ID_SOLICITANTE) REFERENCES USUARIO (ID),
		CONSTRAINT FK_SOLICITACAO_ID_SOLICITADO FOREIGN KEY (ID_SOLICITADO) REFERENCES USUARIO (ID)
);

CREATE TABLE PUBLICACAO (
	ID				NUMBER(12) NOT NULL,
	TEXTO			VARCHAR2(255) NOT NULL,
	DATA_PUBLICACAO	DATE NOT NULL,
		CONSTRAINT PK_PUBLICACAO PRIMARY KEY (ID)
);

CREATE TABLE CURTIDA (
	ID				NUMBER(12) NOT NULL,
	ID_PUBLICACAO	NUMBER(12) NOT NULL,
	ID_USUARIO		NUMBER(12) NOT NULL,
		CONSTRAINT PK_CURTIDA PRIMARY KEY (ID),
		CONSTRAINT FK_CURTIDA_ID_PUBLICACAO FOREIGN KEY (ID_PUBLICACAO) REFERENCES PUBLICACAO (ID),
		CONSTRAINT FK_CURTIDA_ID_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID)
);

CREATE TABLE COMENTARIO (
	ID				NUMBER(12) NOT NULL,
	ID_PUBLICACAO	NUMBER(12) NOT NULL,
	ID_USUARIO		NUMBER(12) NOT NULL,
	TEXTO			VARCHAR2(255) NOT NULL,
	DATA_COMENTARIO	VARCHAR2(255) NOT NULL,
		CONSTRAINT PK_COMENTARIO PRIMARY KEY (ID),
		CONSTRAINT FK_COMENTARIO_ID_PUBLICACAO FOREIGN KEY (ID_PUBLICACAO) REFERENCES PUBLICACAO (ID),
		CONSTRAINT FK_COMENTARIO_ID_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID)
);

CREATE SEQUENCE SEQ_USUARIO
    MINVALUE        1
    MAXVALUE        999999999999
    START WITH      1
    INCREMENT BY    1
    NOCACHE
    NOCYCLE;
	
CREATE SEQUENCE SEQ_AMIZADE
    MINVALUE        1
    MAXVALUE        999999999999
    START WITH      1
    INCREMENT BY    1
    NOCACHE
    NOCYCLE;
	
CREATE SEQUENCE SEQ_SOLICITACAO_AMIZADE
    MINVALUE        1
    MAXVALUE        999999999999
    START WITH      1
    INCREMENT BY    1
    NOCACHE
    NOCYCLE;
	
CREATE SEQUENCE SEQ_PUBLICACAO
    MINVALUE        1
    MAXVALUE        999999999999
    START WITH      1
    INCREMENT BY    1
    NOCACHE
    NOCYCLE;
	
CREATE SEQUENCE SEQ_CURTIDA
    MINVALUE        1
    MAXVALUE        999999999999
    START WITH      1
    INCREMENT BY    1
    NOCACHE
    NOCYCLE;
	
CREATE SEQUENCE SEQ_COMENTARIO
    MINVALUE        1
    MAXVALUE        999999999999
    START WITH      1
    INCREMENT BY    1
    NOCACHE
    NOCYCLE;
	
	/*
DROP TABLE AMIZADE;
DROP TABLE COMENTARIO;
DROP TABLE CURTIDA;
DROP TABLE PUBLICACAO;
DROP TABLE SOLICITACAO_AMIZADE;
DROP TABLE USUARI0;

DROP SEQUENCE SEQ_AMIZADE;
DROP SEQUENCE SEQ_COMENTARIO;
DROP SEQUENCE SEQ_CURTIDA;
DROP SEQUENCE SEQ_PUBLICACAO;
DROP SEQUENCE SEQ_SOLICITACAO_AMIZADE;
DROP SEQUENCE SEQ_USUARIO;
	*/